apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: medical-qa
data:
  CHROMA_MODE: "server"
  CHROMA_HOST: "chromadb"
  CHROMA_PORT: "8000"
  SEED_URL: "${SEED_URL}"
  UPSTAGE_API_KEY: "${UPSTAGE_API_KEY}"
  SERPER_API_KEY: "${SERPER_API_KEY}"